export const sqlAuth = `
  SELECT
    MATRICULA AS "id"
    , NOME AS "name"
    , NOME_GUERRA AS "username"
FROM PCEMPR
WHERE NOME_GUERRA = UPPER(:LOGIN)
  AND decrypt(SENHABD, USUARIOBD) = UPPER(:SENHA)
  AND SITUACAO = 'A'
`;

export const sqlUserData = ` 
  SELECT 
    NOME as "name"
    , NOME_GUERRA AS "username"
    , MATRICULA AS "id"
  FROM PCEMPR
  WHERE MATRICULA = :MATRICULA
`;

export const sqlGetAcessos = `
  SELECT
      NVL(AUDITORIA.ACESSO, 'N') AS "auditoriaEnderecos"
      , NVL(SEPARACAO.ACESSO, 'N') AS "separacaoMercadorias"
      , NVL(CONSULTAENDER.ACESSO, 'N') AS "consultaEnderecos"
      , NVL(CONSULTAPROD.ACESSO, 'N') AS "consultaProdutos"
  FROM PCEMPR EMPR
  LEFT JOIN PCCONTROI AUDITORIA
      ON EMPR.MATRICULA = AUDITORIA.CODUSUARIO 
      AND AUDITORIA.CODCONTROLE = 1
      AND AUDITORIA.CODROTINA = 11000
  LEFT JOIN PCCONTROI SEPARACAO
      ON EMPR.MATRICULA = SEPARACAO.CODUSUARIO
      AND SEPARACAO.CODCONTROLE = 2
      AND SEPARACAO.CODROTINA = 11000
  LEFT JOIN PCCONTROI CONSULTAENDER
      ON EMPR.MATRICULA = CONSULTAENDER.CODUSUARIO 
      AND CONSULTAENDER.CODCONTROLE = 3
      AND CONSULTAENDER.CODROTINA = 11000
  LEFT JOIN PCCONTROI CONSULTAPROD
      ON EMPR.MATRICULA = CONSULTAPROD.CODUSUARIO 
      AND CONSULTAPROD.CODCONTROLE = 4
      AND CONSULTAPROD.CODROTINA = 11000
  WHERE EMPR.MATRICULA = :CODUSUARIO
`;

export const sqlDeleteRefreshTokenAntigos = `
  DELETE FROM BOAPIREFRESHTOKEN WHERE EXPIRACAO < SYSDATE
`;

export const sqlInsertRefreshToken = `
  INSERT INTO BOAPIREFRESHTOKEN (TOKEN, MATRICULA, EXPIRACAO)
  VALUES (:TOKEN, :MATRICULA, SYSDATE + 7)`;

export const sqlGetDadosRefreshToken = `
  SELECT MATRICULA as "id"
  FROM BOAPIREFRESHTOKEN
  WHERE TOKEN = :TOKEN
  AND EXPIRACAO >= SYSDATE
  `;
